module Viz.DeJong exposing (viz)

{-| **De Jong attractor** — the orbit of `x′ = sin(a·y) − cos(b·x)`, `y′ = sin(c·x) − cos(d·y)`. Four
parameters trace out an airy, structured point cloud, a cousin of the Clifford attractor.
-}

import Color
import Draw
import Form
import Html exposing (Html)
import Svg exposing (Svg)
import Value
import Viz exposing (Viz)


type alias Model =
    { a : Float
    , b : Float
    , c : Float
    , d : Float
    , points : Int
    , stroke : String
    }


viz : Viz
viz =
    { kind = "dejong"
    , name = "De Jong attractor"
    , description = "An airy, structured strange-attractor cloud."
    , about = "The Peter de Jong attractor is generated by iterating a pair of trigonometric maps, mixing the two coordinates through sines and cosines. Like the Clifford attractor it is a \"strange attractor\": the orbit never settles or repeats, yet it is forever confined to a delicate, self-organising cloud.\n\nFour numbers tune an endless variety of veils, knots and lattices. It has no special scientific meaning — it is prized purely as a generator of intricate, surprising beauty from a two-line rule, and is a staple of algorithmic art."
    , starter = toSource default
    , movable = False
    , render = \source -> Result.map prepare (decode source)
    , controls = controls
    }


default : Model
default =
    { a = 1.4, b = -2.3, c = 2.4, d = -2.1, points = 45000, stroke = "#67e8f9" }



-- DECODE / PRINT ----------------------------------------------------------------------------------


decode : String -> Result String Model
decode source =
    Value.parseScene source
        |> Result.andThen Value.record
        |> Result.andThen
            (\fs ->
                Result.map5 (\a b c d points -> ( a, b, ( c, d, points ) ))
                    (Value.numField "a" fs)
                    (Value.numField "b" fs)
                    (Value.numField "c" fs)
                    (Value.numField "d" fs)
                    (Value.intField "points" fs)
                    |> Result.andThen
                        (\( a, b, ( c, d, points ) ) ->
                            Result.map (\stroke -> Model a b c d points stroke)
                                (Value.strField "stroke" fs)
                        )
            )


toSource : Model -> String
toSource d =
    Value.header
        ++ "    { kind = \"dejong\"\n    , a = "
        ++ Value.numStr d.a
        ++ "\n    , b = "
        ++ Value.numStr d.b
        ++ "\n    , c = "
        ++ Value.numStr d.c
        ++ "\n    , d = "
        ++ Value.numStr d.d
        ++ "\n    , points = "
        ++ String.fromInt d.points
        ++ "\n    , stroke = \""
        ++ d.stroke
        ++ "\"\n    }\n"



-- RENDER ------------------------------------------------------------------------------------------


prepare : Model -> (String -> Float -> Svg msg)
prepare d =
    let
        raw =
            orbit d (clamp 1000 80000 d.points)

        ( cx, cy, scale ) =
            Draw.fitTransform raw

        pts =
            List.map (\( x, y ) -> ( (x - cx) * scale, -(y - cy) * scale )) raw
    in
    \mode phase -> Draw.stage [ Draw.cloud "0.7" (Color.resolve mode d.stroke) phase pts ]


orbit : Model -> Int -> List ( Float, Float )
orbit d count =
    let
        step _ ( x, y, acc ) =
            let
                nx =
                    sin (d.a * y) - cos (d.b * x)

                ny =
                    sin (d.c * x) - cos (d.d * y)
            in
            ( nx, ny, ( nx, ny ) :: acc )

        ( _, _, pts ) =
            List.foldl step ( 0.1, 0.1, [] ) (List.range 1 count)
    in
    List.drop 10 (List.reverse pts)



-- CONTROLS ----------------------------------------------------------------------------------------


controls : String -> Html String
controls source =
    case decode source of
        Err e ->
            Form.note ("This file isn't a De Jong attractor yet — " ++ e)

        Ok d ->
            Form.controls
                [ Form.group "Parameters"
                    [ Form.slider "a" -3 3 0.01 d.a (\v -> toSource { d | a = v })
                    , Form.slider "b" -3 3 0.01 d.b (\v -> toSource { d | b = v })
                    , Form.slider "c" -3 3 0.01 d.c (\v -> toSource { d | c = v })
                    , Form.slider "d" -3 3 0.01 d.d (\v -> toSource { d | d = v })
                    ]
                , Form.group "Cloud"
                    [ Form.slider "points" 5000 80000 1000 (toFloat d.points) (\v -> toSource { d | points = round v })
                    , Form.colorRow "stroke" d.stroke (\s -> toSource { d | stroke = s })
                    ]
                , Form.group "Presets"
                    [ Form.presets
                        [ Form.preset "Veil" (toSource { d | a = 1.4, b = -2.3, c = 2.4, d = -2.1 })
                        , Form.preset "Knot" (toSource { d | a = 2.01, b = -2.53, c = 1.61, d = -0.33 })
                        , Form.preset "Lattice" (toSource { d | a = -2.7, b = -0.09, c = -0.86, d = -2.2 })
                        , Form.preset "Star" (toSource { d | a = -2.24, b = 0.43, c = -0.65, d = -2.43 })
                        , Form.preset "Drift" (toSource { d | a = 1.641, b = 1.902, c = 0.316, d = 1.525 })
                        ]
                    ]
                ]
